#!/bin/bash
set -e

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
cd $SCRIPT_DIR

if [ ! -f "$SCRIPT_DIR/venv/bin/python" ]; then
    echo "Can't find Python Virtual Enviorment."
    exit 1
fi

if ! "$SCRIPT_DIR/venv/bin/python" "$SCRIPT_DIR/main.py"; then
    echo "Cant execute."
    exit 1
fi
